### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by styper** [m-manu/rsync-sidekick#11]
First of let me say that this is an amazing tool, definitely saving up a lot of time on rsync operations.

I have two suggestions:
1. Allow the user to set the output .sh name like: --shellscript my_shell.sh
2. Order by path ascending when defining the operations inside the output shell script. This has no practical effect, I just thought I was doing something wrong when I:

> Generated a .sh file

> Renamed one file by hand on dest

> Generated a second .sh file

> Compared both sh files on Win merge, and they were 95% different, but just the ordering was different in them

**Comment by m-manu** [comment]
@styper Latest version (v1.5.0) implements a special flag for this.
