### ISSUE TITLE
"go get" seems to fail upfront

### ISSUE THREAD

**Issue by seatedscribe** [m-manu/rsync-sidekick#2]
Hello there, finally happy top find someone like-minded that put the effort to actually write a program that was in my mind for a long time! :)

I am not an expert in go, and was giving a shot at your program but am having an issue while trying to install:
`me@host:~$ go get github.com/m-manu/rsync-sidekick`
`package embed: unrecognized import path "embed" (import path does not begin with hostname)`
`package io/fs: unrecognized import path "io/fs" (import path does not begin with hostname)`

After this the script seems to keep going on, and after a few seconds it returns without any message, but I cannot invoke nor find any `rsync-sidekick` executable.

The test system is quite "old" but regularly updated, and I found the go version is in the same shape (many version behind):
`me@host:~$ go version`
`go version go1.10.4 linux/amd64`

Any hint as to make your program run on this platform?
Thanks in advance 😉

**Comment by m-manu** [comment]
You're on Go 1.10. For this tool to work with `go get`, you need Go 1.16

**Comment by seatedscribe** [comment]
I suspected this. Is there an alternative way for installing then?
Sorry for asking basic questions, it's just I never worked with this tools (yet)

**Comment by m-manu** [comment]
If you can't upgrade to Go 1.16, you've two options:

 1. Use Docker (see README)
 2. Temporarily upgrade to Go 1.16. Do `go get` (this creates executable). Then go back to old version that you need it to be.
