### ISSUE TITLE
Current installation instructions are not compatible with latest Go (1.18.1)

### ISSUE THREAD

**Issue by pineapplemachine** [m-manu/rsync-sidekick#5]
This utility cannot be installed using the command listed in the readme as of at least Go 1.18.1: `go get github.com/m-manu/rsync-sidekick`

I believe it should be installed this way instead: `go install github.com/m-manu/rsync-sidekick@latest`

**Comment by m-manu** [comment]
@pineapplemachine Yes, till recently, this tool was built on Go 1.16. It has now been upgraded to Go 1.17 and documentation has been updated. Check now.
