### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by cbzittoun** [m-manu/rsync-sidekick#6]
Hi,

I installed go:
```
ll /usr/local/go
total 244
drwxr-xr-x 10 root root   4096 May 10 18:51 ./
drwxr-xr-x 11 root root   4096 May 18 11:57 ../
drwxr-xr-x  2 root root   4096 May 10 18:48 api/
-rw-r--r--  1 root root  56057 May 10 18:48 AUTHORS
drwxr-xr-x  2 root root   4096 May 10 18:50 bin/
-rw-r--r--  1 root root     52 May 10 18:48 codereview.cfg
-rw-r--r--  1 root root   1339 May 10 18:48 CONTRIBUTING.md
-rw-r--r--  1 root root 111408 May 10 18:48 CONTRIBUTORS
drwxr-xr-x  2 root root   4096 May 10 18:48 doc/
drwxr-xr-x  3 root root   4096 May 10 18:48 lib/
-rw-r--r--  1 root root   1479 May 10 18:48 LICENSE
drwxr-xr-x 12 root root   4096 May 10 18:48 misc/
-rw-r--r--  1 root root   1303 May 10 18:48 PATENTS
drwxr-xr-x  6 root root   4096 May 10 18:51 pkg/
-rw-r--r--  1 root root   1475 May 10 18:48 README.md
-rw-r--r--  1 root root    397 May 10 18:48 SECURITY.md
drwxr-xr-x 48 root root   4096 May 10 18:48 src/
drwxr-xr-x 27 root root  12288 May 10 18:48 test/
-rw-r--r--  1 root root      8 May 10 18:48 VERSION

go version
go version go1.18.2 linux/amd64

echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin
```

but the first time I run `go install github.com/m-manu/rsync-sidekick@latest`, I only get:
```
go: downloading github.com/m-manu/rsync-sidekick v1.3.0
go: downloading golang.org/x/text v0.3.7
```

the following times i run `go install github.com/m-manu/rsync-sidekick@latest`, I get nothing.

and the go bin directory does not contain rsync-sidekick:
```
ll /usr/local/go/bin
total 17484
drwxr-xr-x  2 root root     4096 May 10 18:50 ./
drwxr-xr-x 10 root root     4096 May 10 18:51 ../
-rwxr-xr-x  1 root root 14542442 May 10 18:50 go*
-rwxr-xr-x  1 root root  3350528 May 10 18:50 gofmt*
```

What did I do wrong?

**Comment by m-manu** [comment]
@cbzittoun @sagitariozod This is something I had missed earlier before realizing `go install` command installs `$HOME/go/bin` directory. I'd recommended adding below line to your `.zshrc`/`.bashrc` file:
```
export PATH="$PATH:$HOME/go/bin"
```

Let me know if it works.

**Comment by m-manu** [comment]
@cbzittoun @sagitariozod `go install` command installs in `$GOPATH/bin` directory, which is typically `$HOME/go/bin`. I'd recommended adding below line to your `.zshrc`/`.bashrc` file:
```
export PATH="$PATH:$HOME/go/bin"
```
Let me know if this fixed the issue.

**Comment by cbzittoun** [comment]
it works for me
thanks a lot
👍

**Comment by cbzittoun** [comment]
thanks for the tool, it seems to be working just fine!

please note that, combined with rsnapshot, it saves (1) time but also **(2) storage**

howto:
create a script eg. `/path/to/scripts/rsync-with-sidekick.sh` containing:
```
/root/go/bin/rsync-sidekick /some/folder/ /path/to/snapshots/alpha.0/localhost/some/folder/
/usr/bin/rsync "$@"
```

then in `/etc/rsnapshot.conf`, add the param:
```
cmd_rsync       /path/to/scripts/rsync-with-sidekick.sh
```

this fudge is prefered to using the rsnapshot param `cmd_preexec`, as by using that param, `rsync-sidekick` would alter `alpha.0` before it gets copied and rebranded `alpha.1`

just mentioning that as it could be added to the readme as an additional usecase

thanks again
